name: Build and Push Backend

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'   # only triggers when backend files change

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: yashgaonkar18/hack-backend:latest